---
title: "homework_1210"
author: "홍영화"
date: "2018년 12월 15일"
output: html_document
---

#1.필요한 패키지
```{r}
library(ggplot2)
library(dplyr)
library(rpart)
library(rpart.plot)
```

#2.파일 불러오기
```{r}
baseball_raw <- read.csv('BaseballHitters.csv')
baseball <- subset(baseball_raw, select= -c(league87,team87))
baseball <- baseball[-c(177,294,44,220,215,25,81,111,107,284,216,36,18,56,91,320,113,194,321,151,7,19,242,123,221,230,45,277,54,228,156,298,92,121,181,243,191,68,118,55,264,153,125,102,75,32,303,317,106,252,149,70,316,293,40,310,90,100,258,15),]
```

#3.데이터 살펴보기
```{r}
#결측치 확인하기 --> salary87에만 결측치가 존재한다.
colSums(is.na(baseball))  

#결측치 제외하기
baseball <- baseball %>% filter(is.na(salary87) == FALSE)
colSums(is.na(baseball))
summary(baseball)

```

#4-1.선형회귀분석
```{r}
#선형회귀 모형A
fitA <- lm(salary87~.,data=baseball %>% select(-c('X','firstName','lastName')))
summary(fitA)
mean((baseball$salary87 - predict(fitA))^2)       #MSE=51262.76

#다음 변수값이 통계적으로 유의하다고 판단됨
#Coefficients:
#               Estimate Std. Error t value Pr(>|t|)    
#(Intercept)   252.32670  411.77937   0.613 0.540943 
#AB86           -2.24003    0.73944  -3.029 0.002881 ** 
#H86             8.96594    2.62271   3.419 0.000808 ***
#careerR         1.92198    0.83604   2.299 0.022873 *  
#careerW        -0.80257    0.34332  -2.338 0.020710 * 
#team86Pit.   -618.58129  268.01721  -2.308 0.022348 *  
#position862S  703.20135  351.82252   1.999 0.047420 *  
#position863B  449.37846  217.00221   2.071 0.040064 * 
#position86C   320.69334  120.84284   2.654 0.008805 ** 
#position86S3 1153.53624  404.05109   2.855 0.004906 **
#position86SS  469.84996  227.51814   2.065 0.040611 *  
#PO86            0.54075    0.21435   2.523 0.012675 *  


#선형회귀 모형b
##유의하다고 판단된 변수 중 하나만 추출하여 회귀분석
fitB <- lm(salary87~H86,data=baseball)
#summary(fitB)
mean((baseball$salary87 - predict(fitB))^2)     #MSE=144303.3

ggplot(data=baseball, aes(x=H86, y=salary87)) + geom_point() +
    geom_smooth(method='lm')


#선형회귀 모형C
##유의하다고 판단된 변수들 모두 추출하여 회귀분석
fitC <- lm(salary87~AB86+H86+W86+careerR+careerW+team86+position86+PO86,data=baseball)
#summary(fitC)
mean((baseball$salary87 - predict(fitC))^2)     #MSE=59597.94


#선형회귀 모형D
##그 변수들끼리 interaction 적용하여 회귀분석
fitD <- lm(salary87~AB86+H86+W86+careerR+careerW+PO86+team86*position86,data=baseball)
#summary(fitD)
mean((baseball$salary87 - predict(fitD))^2)     #MSE=4528.309


#선형회귀 모형E
##여러 변수에 interection 적용하여 회귀분석
fitE <- lm(salary87~AB86+H86*W86+careerR*careerW+PO86+team86*position86,data=baseball)
#summary(fitE)
mean((baseball$salary87 - predict(fitE))^2)     #MSE=3680.111


#선형회귀 모형F
##모든 변수에 interaction 적용하여 회귀분석...(?)
fitF <- lm(salary87~AB86*H86*W86*careerR*careerW*PO86*team86*position86,data=baseball)
#summary(fitF)
mean((baseball$salary87 - predict(fitF))^2)     #MSE=3.094031e-21

#MSE값이 가장 작은 모형e가 가장 적합하다. (?)


```

#4-2.선형회귀분석 시각화
```{r}
#ggPredict(fitF,interactive=TRUE)
```


#5.배깅 결정나무
```{r}
#결정나무 모형A
fitG <- rpart(salary87~., baseball %>% select(-c("X", 
    "firstName", "lastName")), control = rpart.control(maxdepth=4))
summary(fitG)
plot(fitG, main='Decision Tree A')
text(fitG)
rpart.plot(fitG) 

#Node number 4: 50 observations
#  mean=123.32, MSE=2371.038 


#결정나무 모형B
fitH <- rpart(salary87~., baseball %>% select(-c("X", 
                                                 "firstName", "lastName","AB86", "HR86" , "RBI86" , "years" , "careerH" , "careerHR" , "league86", "A86")), control = rpart.control(maxdepth=4))
summary(fitH)
plot(fitH, main='Decision Tree B')
text(fitH)
rpart.plot(fitH)

#Node number 4: 74 observations
#  mean=162.2658, MSE=5993.583 


#결정나무 모형C
fitI <- rpart(salary87~AB86+H86+W86+careerR+careerW+team86+position86+PO86, baseball %>% select(-c("X", 
    "firstName", "lastName")), control = rpart.control(maxdepth=4))
summary(fitI)

plot(fitI, main='Decision Tree C')
text(fitI)
rpart.plot(fitI) 

#Node number 4: 74 observations
#  mean=162.2658, MSE=5993.583 


#배깅 결정나무는 interaction 적용이 불가능하다
#MSE값이 가장 작은 결정나무 모형A가 가장 적합하다.(?)

```





