---
title: "2018-09-14 첫 번째 수업"
author: "김권현"
date: "2018년 9월 14일"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# HBE01239: 응용데이터사이언스(5733)

* 담당교수 : 김권현

* 강의시간 : 금요일 오후 1:30 - 4:15

* 강의장소 : S1353

* 상담시간 : 금요일 수업 전후(이메일로 사전 약속 필요)

* 선수과목 : R통계분석

## 교과목 개요

'R통계분석'에 기초하여 상위 과정의 R 사용법과 프로그래밍 능력을 배양한다. 

## 성적평가방법

출석(20), 과제물/보고서(20), 수시시험 및 중간고사(20), 학기말시험(20), 발표(20)

***

## R markdown

* [R markdown](https://rmarkdown.rstudio.com/lesson-1.html)


## 깃헙(github) 관련

* [github](https://github.com/) id를 만든다.

* [수업 레포지토리](https://github.com/kwhkim/MJU-2018-02-DataScience)를 fork한다.

* Rstudio - New Project - Version Control - Git - Clone Git Repository

* [git-scm download](https://git-scm.com/downloads)

* 자신의 수정 사항 Git에 올리기 : Stage - Commit - Push -- New Pull Request

* Configuring a remote for a fork

```
     $ git remote -v
     $ remote add upstream https://github.com/kwhkim/MJU-2018-02-DataScience.git
     $ git remote -v
```
  
* Syncing a fork

```
     $ git fetch upstream
     $ git checkout master
     $ git merge upstream/master
```


## 데이터

* [공공데이터포털](https://www.data.go.kr/)

* [서울열린데이터광장](http://data.seoul.go.kr/)

* [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php)

* [www.statsci.org](www.statsci.org)

* [Kaggle](https://www.kaggle.com/)

* [FRED, Economic Research](https://fred.stlouisfed.org/)

* [the National Bureau of Economic Research](http://www.nber.org/data/)

* [통계지리정보서비스](https://sgis.kostat.go.kr/view/index)

* [Journal of open psychology data](https://openpsychologydata.metajnl.com/)

* [Academic Torrents](http://academictorrents.com/)


## 통계학과 R 관련 자료

* [R과 함께 하는 통계학의 이해](http://www.bigbook.or.kr/bbs/bbs/board.php?bo_table=bo16&sca=&sfl=wr_subject&stx=%C5%EB%B0%E8%C7%D0%C0%C7+%C0%CC%C7%D8&x=0&y=0)

* [Learning statistics with R](http://www.fon.hum.uva.nl/paul/lot2015/Navarro2014.pdf)

* [Quick-R](https://www.statmethods.net/about/sitemap.html)

* [r4stats](http://r4stats.com)

* [r-tutor](www.r-tutor.com)

* [Introduction to Statistical Thought](http://people.math.umass.edu/~lavine/Book/book.pdf)

* [Data Science Books](http://www.wzchen.com/data-science-books/)

* [Free Stats e-book](https://www.r-statistics.com/2009/10/free-statistics-e-books-for-download/)


## R로 데이터 불러들이기(Importing Data)

* http://r4stats.com/examples/data-import/

* http://www.r-tutor.com/r-introduction/data-frame/data-import

* http://www.cookbook-r.com/Data_input_and_output/Loading_data_from_a_file/




