---
title: "ggplot2_lines"
author: "KwH Kim"
date: "2018년 10월 18일"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.height=3)
knitr::opts_chunk$set(fig.width=3)
library(ggplot2)
library(dplyr)
```

## Key components of every plot
1. Data
2. Aesthetic mapping
3. Geoms
4. **Auxillary lines**
    - `geom_hline(yintercept= , col= , size= , linetype= )`
    - `geom_vline(xintercept= , col= , size= , linetype= )`
    - `geom_abline(intercept= , col= , slope= )`
    
linetypes
```{r fig.height=1.5, fig.width=6, results=F, echo= F}
lty <- c("solid", "dashed", "dotted", "dotdash", "longdash", "twodash")
linetypes <- data.frame(
  y = seq_along(lty),
  lty = lty
) 
ggplot(linetypes, aes(0, y)) + 
  geom_segment(aes(xend = 5, yend = y, linetype = lty)) + 
  scale_linetype_identity() + 
  geom_text(aes(label = lty), hjust = 0, nudge_y = 0.2) +
  scale_x_continuous(NULL, breaks = NULL) + 
  scale_y_reverse(NULL, breaks = NULL)
```
    

