---
title: "1019 과제"
author: "23 이도휘"
date: "2018.10.18"
output: html_document
---

#SUMMARY

```{r}
library(dplyr)
data01 <- read.csv("C://Users//gfdss//Desktop//datascience//homework1//MJU-2018-02-DataScience//도로교통공단_전국_사망교통사고_2017.csv")
tb01 = as_tibble(data01)
tb01 %>% group_by(state) %>% summarise(mean(death), min(death), max(death), sd(death))
```

```{r}
library(dplyr)
data02 <- read.csv("C://Users//gfdss//Desktop//datascience//homework1//MJU-2018-02-DataScience//사망교통사고.csv")
tb02 = as_tibble(data02)
tb02 %>% group_by(state) %>% summarise(mean(death), min(death), max(death), sd(death))

```

```{r}
library(dplyr)
data03 <- read.csv("C://Users//gfdss//Desktop//datascience//homework1//MJU-2018-02-DataScience//음주운전 교통사고.csv")
tb03 = as_tibble(data03)
tb03 %>% group_by(state) %>% summarise(mean(death), min(death), max(death), sd(death))
```


**새로운 사실**

*지역별 교통사고 사건 당 평균 사망자수는 1명이다.(data01)
 
  -2017년 지역별 교통사고 평균 사망자수는 약 20명이다.(data02)
 
  -이 중 음주운전 교통사고 평균 사망자수는 약 1.87명이다.(data03)
  
#JOIN

```{r}
options(max.print=99999)
library(dplyr)
data04 <- left_join(data01, data02, data03, by = "state")
head(data04)

```

#가로형_세로형

```{r}
options(max.print=99999)
library(dplyr)
library(tidyr)
data04$state = rownames(data04); rownames(data04) = NULL
data04 %>% select(state, death.x, death.y) -> accident01
head(accident01)

accident01 %>% gather(key='feature', value='value', death.x, death.y) -> accidentLong
head(accidentLong)

accidentLong %>% spread(key='feature', value='value') -> accident02
head(accident02)

all.equal(accident01, accident02)

```

**새로운 사실**

*left_join 후 data01의 death는 death.x로, data02와 data03의 death는 death.y라는 변수로 통합되면서 
지역별 사고 당 사망자수와 지역별 전체 사망자수(음주운전사고 사망자수 포함)를 비교할 수 있게 되었다.

