---
title: "hw4-예측변수 yd와 결과변수 sl로 선형회귀분석하기"
author: "60140275_장민"
date: "2018년 11월 15일"
output: html_document
---
```{r}
library(readr)
salary <- read_table2("http://data.princeton.edu/wws509/datasets/salary.dat")
View(salary)

lm(sl ~ yd, salary)
a <- lm(sl~yd, salary)
print(a)
coef(a)
fitted(a)
residuals(a)
confint(a)
```

# 1. 계수 추정하기

```{r}
print(a)
```



# 2. 계수의 95% 신뢰구간 구하기

```{r}
t.test(salary$sl, conf.level=0.95)
t.test(salary$yd, conf.level=0.95)
```

# 3. 데이터와 적합한 회귀선 시각화 하기

```{r}
library(ggplot2)

plot(a)

plot(sl ~ yd, salary, main='회귀분석 결과 시각화 a'); abline(coef(a))

 ggplot(salary, aes(x=yd, y=sl)) + geom_point() + 
     geom_smooth(method="lm") + labs(title='회귀분석 결과 시각화 b')
```

# 4. 선형회귀분석 결과 진단하기

```{r}
par(mfrow=c(2,2),oma = c(0, 0, 2, 0))
plot(a, main='04. 회귀분석 가정 검토')

plot(a, which=1:6)

anova(a)

full <- lm(sl ~ yd, data=salary)
reduced <- lm(sl ~ 1, data=salary)

anova(reduced, full)
```

* 모델을 비교한 결과 F통계량은 41.815이며, p값은 아주 작게 나타난다. 
* 따라서 reduced 모델과 full 모델 간 유의한 차이가 있다는 결론을 내릴 수 있다. 
* 즉, yd열이 유의미한 예측변수임을 뜻한다.

