---
title: "강의용"
author: "knock"
date: "2018년 9월 21일"
output: html_document
---

#제목 

**굵어** _기울어_

ul

* 1번
    - 하나둘셋넷 띄고 대쉬 띄고 하면 ul밑에 있는 ul
* 2번
* 3번


link_to <http://sso.mju.ac.kr> 

---

```{r}
name = c("hwang", "nak", "joo")
height = c(180, 185, 190)
weight = c(1, 2, 3)
table1 <- data.frame(name, height, weight)
print(table1)
```

우리는 이름이 `r name`인 자료를 가지고 있따.

테이블만들기
https://www.tablesgenerator.com/markdown_tables# 을 이용하자

| 하나  | 둘  |  셋 |
|---|:-:|--:|
|   1|2   | 3  |
|   원|  투 |쓰리   |



이렇게 했더라

```{r echo = F, results = "hold", warning = F}
data(mtcars)
dat <- mtcars
cat("First 5 rows of data 'mtcars'")
head(dat)
cat("Relation between qsec(Second for Quarter Mile), hp(Horse Power) and wt(Weight)")
plot(qsec ~ I(hp/wt), data=dat)
```


부가 서비스를 전부 제외하고 싶다면 이발해! eval = F
```{r eval = F}
data(mtcars)
dat <- mtcars
cat("First 5 rows of data 'mtcars'")
head(dat)
cat("Relation between qsec(Second for Quarter Mile), hp(Horse Power) and wt(Weight)")
plot(qsec ~ I(hp/wt), data=dat)
```


---

일부분 보여주기 caption 이용법

```{r}
data(mtcars)
knitr::kable(df, caption='')  #또는 DT::datatable(df, caption=''), install.package("DT")
dat <- mtcars
cat("First 5 rows of data 'mtcars'")
head(dat)
cat("Relation between qsec(Second for Quarter Mile), hp(Horse Power) and wt(Weight)")
plot(qsec ~ I(hp/wt), data=dat)
```




